# Generated by Django 5.1.6 on 2025-04-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_tft', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('new_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_club', to='main.club')),
                ('old_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_club', to='main.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season')),
            ],
        ),
    ]
