# Generated by Django 5.1.6 on 2025-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
